/**
 * PropertyDetailPage.jsx
 * 
 * Individual property page — accessed from /property/:id
 * Pulls property data by ID from a shared data file.
 * Data source: frontend/src/data/properties.js
 * Description: generated by Gemini API via backend cache
 */

import { useParams, useNavigate } from 'react-router-dom'
import { motion } from 'motion/react'
import { useState, useEffect, useRef } from 'react'
import Navbar  from '@/components/layout/Navbar'
import Footer  from '@/components/layout/Footer'
import { FadeUp } from '@/components/ui/AnimatedText'
import {
  MapPin, BedDouble, Bath, Maximize, ArrowLeft,
  ArrowRight, Heart, Share2, Calendar,
  Home, Wifi, Car, Waves, Trees, Shield,
} from 'lucide-react'
import { getPropertyById } from '@/data/properties'

const fmt = (n) => n >= 1000000
  ? '$' + (n/1000000).toFixed(2) + 'M'
  : '$' + Number(n).toLocaleString()

const FEATURE_ICONS = {
  'Private Pool': Waves, 'Pool & Spa': Waves, 'Resort Pool': Waves, 'Private Beach': Waves,
  'Plunge Pool': Waves, 'Infinity Pool': Waves, 'Heated Pool': Waves,
  'Smart Home': Wifi, 'High-Speed WiFi': Wifi,
  '3-Car Garage': Car, '4-Car Garage': Car, 'Parking': Car, 'Valet': Car,
  'Garden': Trees, 'Desert Views': Trees, 'Mountain Views': Trees,
  'Walled Garden': Trees, 'Italian Gardens': Trees, 'Tropical Garden': Trees,
  'Concierge': Shield, '24hr Doorman': Shield, 'Gated Entry': Shield,
}

/* ── Leaflet map ── */
function PropertyMap({ prop }) {
  const mapRef      = useRef(null)
  const instanceRef = useRef(null)

  useEffect(() => {
    if (!prop?.lat || instanceRef.current) return
    const loadLeaflet = () => {
      if (!window.L) { setTimeout(loadLeaflet, 200); return }
      const L   = window.L
      const map = L.map(mapRef.current, {
        center: [prop.lat, prop.lng], zoom: 14,
        zoomControl: true, attributionControl: false,
      })
      L.tileLayer('https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png', { maxZoom: 19 }).addTo(map)
      const el = document.createElement('div')
      el.style.cssText = 'padding:5px 12px;background:white;border-radius:100px;font-family:Space Mono,monospace;font-size:10px;font-weight:700;color:#111;white-space:nowrap;box-shadow:0 4px 16px rgba(0,0,0,0.3)'
      el.textContent = fmt(prop.price)
      L.marker([prop.lat, prop.lng], {
        icon: L.divIcon({ html: el, className: '', iconSize: [80, 28], iconAnchor: [40, 14] }),
      }).addTo(map)
      instanceRef.current = map
    }
    if (!document.getElementById('leaflet-css')) {
      const link = document.createElement('link')
      link.id = 'leaflet-css'; link.rel = 'stylesheet'
      link.href = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'
      document.head.appendChild(link)
    }
    if (!window.L) {
      const script = document.createElement('script')
      script.src = 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'
      script.onload = loadLeaflet
      document.head.appendChild(script)
    } else {
      loadLeaflet()
    }
    return () => { if (instanceRef.current) { instanceRef.current.remove(); instanceRef.current = null } }
  }, [prop])

  return (
    <div ref={mapRef} style={{ width: '100%', height: '100%', borderRadius: '16px', overflow: 'hidden' }}>
      <style>{'.leaflet-container{background:#0a0a0a!important}'}</style>
    </div>
  )
}

/* ── Gallery strip ── */
function GalleryStrip({ images, heroImg }) {
  const all = [heroImg, ...images].filter(Boolean)
  const [active, setActive] = useState(0)

  return (
    <div>
      <div style={{ width: '100%', aspectRatio: '16/7', overflow: 'hidden', borderRadius: '16px', marginBottom: '10px' }}>
        <motion.img
          key={active}
          src={all[active]}
          alt="Property"
          initial={{ opacity: 0, scale: 1.03 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          style={{ width: '100%', height: '100%', objectFit: 'cover' }}
        />
      </div>
      <div style={{ display: 'flex', gap: '8px', overflowX: 'auto', paddingBottom: '4px' }}>
        {all.map((img, i) => (
          <button key={i} onClick={() => setActive(i)} style={{
            flexShrink: 0, width: '80px', height: '56px',
            borderRadius: '8px', overflow: 'hidden', cursor: 'pointer', padding: 0,
            border: i === active ? '2px solid white' : '2px solid transparent',
            transition: 'border-color 0.2s',
          }}>
            <img src={img} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
          </button>
        ))}
      </div>
    </div>
  )
}

/* ── Page ── */
export default function PropertyDetailPage() {
  const { id }   = useParams()
  const navigate = useNavigate()
  const [liked,         setLiked]         = useState(false)
  const [description,   setDescription]   = useState(null)
  const [displayedText, setDisplayedText] = useState('')

  const prop = getPropertyById(id)

  // Fetch description from Gemini via backend
  useEffect(() => {
    if (!prop) return
    setDescription(null)
    setDisplayedText('')
    const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3001'
    fetch(`${API}/api/properties/${id}/description`)
      .then(r => r.json())
      .then(data => setDescription(data.description))
      .catch(() => setDescription('Description unavailable.'))
  }, [id])

  // Typewriter effect — runs when description arrives
  useEffect(() => {
    if (!description) return
    setDisplayedText('')
    let index = 0
    const interval = setInterval(() => {
      setDisplayedText(prev => prev + description[index])
      index++
      if (index === description.length) clearInterval(interval)
    }, 18)
    return () => clearInterval(interval)
  }, [description])

  if (!prop) return (
    <div style={{ background: '#0a0a0a', minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '16px' }}>
      <Navbar />
      <p style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: '48px', color: 'white' }}>PROPERTY NOT FOUND</p>
      <button onClick={() => navigate(-1)} style={{ fontFamily: 'Space Mono, monospace', fontSize: '11px', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.5)', background: 'transparent', border: '1px solid rgba(255,255,255,0.15)', borderRadius: '100px', padding: '10px 24px', cursor: 'pointer' }}>
        ← GO BACK
      </button>
    </div>
  )

  const isRent = prop.tag === 'FOR RENT'

  return (
    <div style={{ background: '#0a0a0a', minHeight: '100vh' }}>
      <Navbar />

      {/* ── Hero ── */}
      <div style={{ position: 'relative', width: '100%', height: 'clamp(340px, 55vh, 600px)', overflow: 'hidden' }}>
        <img src={prop.img} alt={prop.name}
          style={{ width: '100%', height: '100%', objectFit: 'cover', filter: 'brightness(0.7)' }} />
        <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(to top, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.2) 50%, transparent 100%)' }} />

        <button onClick={() => navigate(-1)} style={{
          position: 'absolute', top: '80px', left: 'clamp(16px,5vw,72px)',
          display: 'flex', alignItems: 'center', gap: '8px',
          fontFamily: 'Space Mono, monospace', fontSize: '10px', letterSpacing: '0.1em',
          color: 'rgba(255,255,255,0.7)', background: 'rgba(0,0,0,0.4)',
          backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,0.2)',
          borderRadius: '100px', padding: '8px 16px', cursor: 'pointer',
        }}>
          <ArrowLeft size={12} strokeWidth={1.5} /> BACK
        </button>

        <div style={{ position: 'absolute', top: '80px', right: 'clamp(16px,5vw,72px)', display: 'flex', gap: '8px' }}>
          <button onClick={() => setLiked(v => !v)} style={{
            width: '36px', height: '36px', borderRadius: '50%',
            background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(8px)',
            border: '1px solid rgba(255,255,255,0.2)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
          }}>
            <Heart size={14} fill={liked ? 'rgba(255,80,80,0.9)' : 'none'} color={liked ? 'rgba(255,80,80,0.9)' : 'white'} />
          </button>
          <button style={{
            width: '36px', height: '36px', borderRadius: '50%',
            background: 'rgba(0,0,0,0.4)', backdropFilter: 'blur(8px)',
            border: '1px solid rgba(255,255,255,0.2)',
            display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
          }}>
            <Share2 size={14} color="white" />
          </button>
        </div>

        <div style={{ position: 'absolute', bottom: 'clamp(24px,4vh,48px)', left: 'clamp(16px,5vw,72px)', right: 'clamp(16px,5vw,72px)' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px', flexWrap: 'wrap' }}>
            <span style={{
              fontFamily: 'Space Mono, monospace', fontSize: '10px', letterSpacing: '0.14em',
              padding: '5px 14px', borderRadius: '100px',
              background: isRent ? 'rgba(100,160,255,0.2)' : 'rgba(255,255,255,0.12)',
              border: isRent ? '1px solid rgba(100,160,255,0.35)' : '1px solid rgba(255,255,255,0.25)',
              color: isRent ? 'rgba(160,210,255,0.9)' : 'rgba(255,255,255,0.85)',
              backdropFilter: 'blur(8px)',
            }}>{prop.tag}</span>
            <span style={{ fontFamily: 'Space Mono, monospace', fontSize: '10px', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.5)', display: 'flex', alignItems: 'center', gap: '5px' }}>
              <MapPin size={11} strokeWidth={1.5} /> {prop.city}, {prop.state}
            </span>
          </div>
          <h1 style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(40px,5.5vw,88px)', color: 'white', lineHeight: 0.9, marginBottom: '12px' }}>
            {prop.name}
            <span style={{ color: 'rgba(255,255,255,0.22)' }}> {prop.type}</span>
          </h1>
          <p style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(22px,3vw,42px)', color: 'rgba(255,255,255,0.9)' }}>
            {fmt(prop.price)}{isRent ? '/mo' : ''}
          </p>
        </div>
      </div>

      {/* ── Main content ── */}
      <div style={{ maxWidth: '1300px', margin: '0 auto', padding: 'clamp(28px,5vh,56px) clamp(16px,5vw,72px)' }}>

        {/* Stats bar */}
        <div style={{
          display: 'flex', gap: '1px', background: 'rgba(255,255,255,0.07)',
          borderRadius: '14px', overflow: 'hidden',
          border: '1px solid rgba(255,255,255,0.07)', marginBottom: '40px', flexWrap: 'wrap',
        }}>
          {[
            { Icon: BedDouble, val: prop.rooms,       label: 'Bedrooms'  },
            { Icon: Bath,      val: prop.baths,       label: 'Bathrooms' },
            { Icon: Maximize,  val: prop.area + ' m²', label: 'Area'    },
            { Icon: Home,      val: prop.type,        label: 'Type'      },
          ].map(({ Icon, val, label }) => (
            <div key={label} style={{ flex: '1 1 140px', padding: '18px 20px', background: 'rgba(10,10,10,0.7)', display: 'flex', flexDirection: 'column', gap: '4px', alignItems: 'flex-start' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <Icon size={13} color="rgba(255,255,255,0.35)" strokeWidth={1.5} />
                <span style={{ fontFamily: 'Space Mono, monospace', fontSize: '8px', letterSpacing: '0.12em', color: 'rgba(255,255,255,0.3)' }}>
                  {label.toUpperCase()}
                </span>
              </div>
              <span style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(18px,2vw,24px)', color: 'white', letterSpacing: '0.03em' }}>
                {val}
              </span>
            </div>
          ))}
        </div>

        {/* Two column layout */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(100%, 500px), 1fr))', gap: 'clamp(24px,5vw,56px)' }}>

          {/* Left col */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '36px' }}>

            {/* Gallery */}
            <FadeUp>
              <h2 style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(22px,2.5vw,32px)', color: 'white', marginBottom: '16px', letterSpacing: '0.04em' }}>
                GALLERY
              </h2>
              <GalleryStrip images={prop.gallery || []} heroImg={prop.img} />
            </FadeUp>

            {/* Description — from Gemini */}
            <FadeUp delay={0.1}>
              <h2 style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(22px,2.5vw,32px)', color: 'white', marginBottom: '14px', letterSpacing: '0.04em' }}>
                ABOUT THIS PROPERTY
              </h2>
              <p style={{ fontFamily: 'DM Sans, sans-serif', fontSize: 'clamp(14px,1.2vw,16px)', lineHeight: 1.85, color: 'rgba(255,255,255,0.45)' }}>
                {displayedText || 'Generating description...'}
              </p>
            </FadeUp>

            {/* Features */}
            <FadeUp delay={0.15}>
              <h2 style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(22px,2.5vw,32px)', color: 'white', marginBottom: '16px', letterSpacing: '0.04em' }}>
                AMENITIES
              </h2>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px,1fr))', gap: '10px' }}>
                {(prop.features || []).map(feat => {
                  const Icon = FEATURE_ICONS[feat] || Shield
                  return (
                    <div key={feat} style={{
                      display: 'flex', alignItems: 'center', gap: '9px',
                      padding: '12px 14px', borderRadius: '10px',
                      background: 'rgba(255,255,255,0.04)',
                      border: '1px solid rgba(255,255,255,0.08)',
                    }}>
                      <Icon size={13} color="rgba(255,255,255,0.4)" strokeWidth={1.5} />
                      <span style={{ fontFamily: 'Space Mono, monospace', fontSize: '9px', letterSpacing: '0.07em', color: 'rgba(255,255,255,0.55)' }}>
                        {feat}
                      </span>
                    </div>
                  )
                })}
              </div>
            </FadeUp>
          </div>

          {/* Right col — sticky */}
          <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>

            {/* CTA card */}
            <FadeUp>
              <div style={{
                position: 'sticky', top: '80px',
                background: 'rgba(255,255,255,0.04)',
                border: '1px solid rgba(255,255,255,0.09)',
                borderRadius: '16px', padding: 'clamp(20px,3vw,32px)',
                display: 'flex', flexDirection: 'column', gap: '16px',
              }}>
                <div>
                  <p style={{ fontFamily: 'Space Mono, monospace', fontSize: '10px', letterSpacing: '0.15em', color: 'rgba(255,255,255,0.3)', marginBottom: '6px' }}>
                    {isRent ? 'MONTHLY RENTAL' : 'ASKING PRICE'}
                  </p>
                  <p style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(28px,4vw,48px)', color: 'white', lineHeight: 1 }}>
                    {fmt(prop.price)}{isRent ? '/mo' : ''}
                  </p>
                </div>

                <div style={{ height: '1px', background: 'rgba(255,255,255,0.07)' }} />

                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{ width: '44px', height: '44px', borderRadius: '50%', overflow: 'hidden', flexShrink: 0, border: '1px solid rgba(255,255,255,0.12)' }}>
                    <img src="https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&q=80" alt="Agent"
                      style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                  </div>
                  <div>
                    <p style={{ fontFamily: 'Space Mono, monospace', fontSize: '11px', letterSpacing: '0.06em', color: 'white', marginBottom: '2px' }}>Marcus Velez</p>
                    <p style={{ fontFamily: 'Space Mono, monospace', fontSize: '9px', letterSpacing: '0.1em', color: 'rgba(255,255,255,0.35)' }}>Senior Real Estate Advisor</p>
                  </div>
                </div>

                <div style={{ height: '1px', background: 'rgba(255,255,255,0.07)' }} />

                <a href="/contact" style={{
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px',
                  padding: '15px', borderRadius: '10px',
                  background: 'white', color: '#111',
                  fontFamily: 'Space Mono, monospace', fontSize: '12px', letterSpacing: '0.12em', fontWeight: 700,
                  textDecoration: 'none',
                }}>
                  <Calendar size={14} strokeWidth={2} />
                  SCHEDULE VISIT
                </a>
                <a href="/agent" style={{
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px',
                  padding: '14px', borderRadius: '10px',
                  border: '1px solid rgba(255,255,255,0.12)',
                  color: 'rgba(255,255,255,0.6)',
                  fontFamily: 'Space Mono, monospace', fontSize: '12px', letterSpacing: '0.12em',
                  textDecoration: 'none', background: 'rgba(255,255,255,0.04)',
                }}>
                  CONTACT AGENT
                  <ArrowRight size={13} strokeWidth={1.5} />
                </a>

                <p style={{ fontFamily: 'Space Mono, monospace', fontSize: '9px', letterSpacing: '0.08em', color: 'rgba(255,255,255,0.22)', textAlign: 'center', lineHeight: 1.6 }}>
                  No commitment required · Free consultation · 24h response
                </p>
              </div>
            </FadeUp>

            {/* Map */}
            {prop.lat && (
              <FadeUp delay={0.1}>
                <h2 style={{ fontFamily: 'Bebas Neue, sans-serif', fontSize: 'clamp(22px,2.5vw,32px)', color: 'white', marginBottom: '14px', letterSpacing: '0.04em' }}>
                  LOCATION
                </h2>
                <div style={{ height: 'clamp(220px,30vh,340px)', borderRadius: '16px', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.08)' }}>
                  <PropertyMap prop={prop} />
                </div>
                <p style={{ fontFamily: 'Space Mono, monospace', fontSize: '10px', letterSpacing: '0.08em', color: 'rgba(255,255,255,0.3)', marginTop: '10px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <MapPin size={11} strokeWidth={1.5} /> {prop.city}, {prop.state}
                </p>
              </FadeUp>
            )}
          </div>
        </div>
      </div>

      <Footer />
    </div>
  )
}
